---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: {{ .Namespace }}
  generateName: {{ .GenerateName }}
  finalizers:
    - {{ .Finalizer }}
  labels:
    {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
spec:
  spec:
    devices:
      requests:
      - name: daemon
        deviceClassName: {{ .DeviceClassName }}
      config:
      - requests: ["daemon"]
        opaque:
          driver: {{ .DriverName }}
          parameters:
            apiVersion: {{ .ComputeDomainDaemonConfig.APIVersion }}
            kind: {{ .ComputeDomainDaemonConfig.Kind }}
            numNodes: {{ .ComputeDomainDaemonConfig.NumNodes }}
            domainID: {{ .ComputeDomainDaemonConfig.DomainID }}
