---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: {{ .Namespace }}
  generateName: {{ .GenerateName }}
  finalizers:
    - {{ .Finalizer }}
  labels:
    {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
    {{ .TargetLabelKey }}: {{ .TargetLabelValue }}
spec:
  spec:
    devices:
      requests:
      - name: daemon
        deviceClassName: {{ .DaemonDeviceClassName }}
      {{ if .ChannelDeviceClassName  }}
      - name: channel
        deviceClassName: {{ .ChannelDeviceClassName }}
      {{- end }}
      config:
      - requests: ["daemon"]
        opaque:
          driver: {{ .DriverName }}
          parameters:
            apiVersion: {{ .DaemonConfig.APIVersion }}
            kind: {{ .DaemonConfig.Kind }}
            numNodes: {{ .DaemonConfig.NumNodes }}
            domainID: {{ .DaemonConfig.DomainID }}
      {{ if .ChannelConfig }}
      - requests: ["channel"]
        opaque:
          driver: {{ .DriverName }}
          parameters:
            apiVersion: {{ .ChannelConfig.APIVersion }}
            kind: {{ .ChannelConfig.Kind }}
            waitForReady: {{ .ChannelConfig.WaitForReady }}
            domainID: {{ .ChannelConfig.DomainID }}
      {{- end }}
